import { ValueType } from 'realgrid';
import { FIELD } from '../utils/constants';

export const Config = [
  {
    fieldName: FIELD.REP_CORP_YN,
    dataType: ValueType.TEXT,
    headerText: '대표 법인',
    header: {
      text: '대표 법인',
    },
    width: 70,
    editable: false,
    textAlignment: 'center',
    visible: true,
    readonly: true,
  },
  {
    fieldName: FIELD.CORP_CODE,
    dataType: ValueType.TEXT,
    headerText: '법인 코드',
    header: {
      text: '법인 코드',
    },
    width: 70,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.CORP_NO,
    dataType: ValueType.TEXT,
    headerText: '법인 번호',
    header: {
      text: '법인 번호',
    },
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.CORP_NAME,
    dataType: ValueType.TEXT,
    headerText: '법인 명',
    header: {
      text: '법인 명',
    },
    width: 150,
    editable: false,
    textAlignment: 'left',
    visible: true,
  },
  {
    fieldName: FIELD.CORP_NAME_EN,
    dataType: ValueType.TEXT,
    headerText: '법인 명(영문)',
    header: {
      text: '법인 명(영문)',
    },
    width: 150,
    editable: false,
    textAlignment: 'left',
    visible: false,
  },
  {
    fieldName: FIELD.CORP_SHT_NAME,
    dataType: ValueType.TEXT,
    headerText: '법인 명(약어)',
    header: {
      text: '법인 명(약어)',
    },
    width: 150,
    editable: false,
    textAlignment: 'left',
    visible: false,
  },
  {
    fieldName: FIELD.PRESIDENT,
    dataType: ValueType.TEXT,
    headerText: '대표자 명',
    header: {
      text: '대표자 명',
    },
    width: 80,
    editable: false,
    textAlignment: 'left',
    visible: true,
  },
  {
    fieldName: FIELD.PRESIDENT_EN,
    dataType: ValueType.TEXT,
    headerText: '대표자 명(영문)',
    header: {
      text: '대표자 명(영문)',
    },
    width: 80,
    editable: false,
    textAlignment: 'left',
    visible: false,
  },
  {
    fieldName: FIELD.PRSD_SEC_NO,
    dataType: ValueType.TEXT,
    headerText: '대표자 번호',
    header: {
      text: '대표자 번호',
    },
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.BIZ_TYPE,
    dataType: ValueType.TEXT,
    headerText: '업태',
    header: {
      text: '업태',
    },
    width: 150,
    editable: false,
    textAlignment: 'left',
    visible: true,
  },
  {
    fieldName: FIELD.BIZ_ITEM,
    dataType: ValueType.TEXT,
    headerText: '업종',
    header: {
      text: '업종',
    },
    width: 150,
    editable: false,
    textAlignment: 'left',
    visible: true,
  },
  {
    fieldName: FIELD.TEL_NO,
    dataType: ValueType.TEXT,
    headerText: '전화 번호',
    header: {
      text: '전화 번호',
    },
    width: 100,
    editable: false,
    textAlignment: 'left',
    visible: true,
  },
  {
    fieldName: FIELD.FAX_NO,
    dataType: ValueType.TEXT,
    headerText: '팩스 번호',
    header: {
      text: '팩스 번호',
    },
    width: 100,
    editable: false,
    textAlignment: 'left',
    visible: true,
  },
  {
    fieldName: FIELD.ZIP_CODE,
    dataType: ValueType.TEXT,
    headerText: '우편 번호',
    header: {
      text: '우편 번호',
    },
    width: 70,
    editable: false,
    textAlignment: 'left',
    visible: false,
  },
  {
    fieldName: FIELD.ADDR,
    dataType: ValueType.TEXT,
    headerText: '주소',
    header: {
      text: '주소',
    },
    width: 200,
    editable: false,
    textAlignment: 'left',
    visible: false,
  },
  {
    fieldName: FIELD.ADDR_EN,
    dataType: ValueType.TEXT,
    headerText: '주소(영문)',
    header: {
      text: '주소(영문)',
    },
    width: 200,
    editable: false,
    textAlignment: 'left',
    visible: false,
  },
  {
    fieldName: FIELD.FOUNDATION_DATE,
    dataType: ValueType.DATE,
    datetimeFormat: 'yyyy/MM/dd',
    headerText: '설립 일자',
    header: {
      text: '설립 일자',
    },
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.REMARK,
    dataType: ValueType.TEXT,
    headerText: '비고',
    header: {
      text: '비고',
    },
    width: 150,
    editable: false,
    textAlignment: 'left',
    visible: false,
  },
  {
    fieldName: FIELD.FIRST_RG_YMS,
    visible: false,
  },
  {
    fieldName: FIELD.FIRST_RG_IDF,
    visible: false,
  },
  {
    fieldName: FIELD.LAST_UPDATE_YMS,
    visible: false,
  },
  {
    fieldName: FIELD.LAST_UPDATE_IDF,
    visible: false,
  },
  {
    fieldName: FIELD.ROW_STAT,
    visible: false,
  },
];
