export const FIELD = {
  REP_CORP_YN: 'rep_corp_yn',
  CORP_CODE: 'corp_code',
  CORP_NAME: 'corp_name',
  CORP_NO: 'corp_no',
  CORP_NAME_EN: 'corp_name_en',
  CORP_SHT_NAME: 'corp_sht_name',
  PRESIDENT: 'president',
  PRESIDENT_EN: 'president_en',
  PRSD_SEC_NO: 'prsd_sec_no',
  BIZ_TYPE: 'biz_type',
  BIZ_ITEM: 'biz_item',
  TEL_NO: 'tel_no',
  FAX_NO: 'fax_no',
  ZIP_CODE: 'zip_code',
  ADDR: 'addr',
  ADDR_EN: 'addr_en',
  FOUNDATION_DATE: 'foundation_date',
  REMARK: 'remark',
  FIRST_RG_YMS: 'first_rg_yms',
  FIRST_RG_IDF: 'first_rg_idf',
  LAST_UPDATE_YMS: 'last_update_yms',
  LAST_UPDATE_IDF: 'last_update_idf',
  ROW_STAT: 'row_stat',
};
