import { ValueType } from 'realgrid';

export const Config = [
  {
    fieldName: 'group_sno',
    dataType: ValueType.NUMBER,
    width: '100',
    textAlignment: 'center',
    editable: false,
    headerText: '그룹 일련번호',
    visible: false,
  },
  {
    fieldName: 'parent_menu_tree_sno',
    dataType: ValueType.TEXT,
    headerText: '부모 트리메뉴 일련번호',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'menu_tree_sno',
    dataType: ValueType.TEXT,
    headerText: '트리메뉴 일련번호',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'menu_sno',
    dataType: ValueType.NUMBER,
    headerText: '메뉴 일련번호',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'run_sno',
    dataType: ValueType.NUMBER,
    headerText: '실행 일련번호',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'menu_name',
    dataType: ValueType.TEXT,
    headerText: '메뉴명',
    width: '350',
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'system_type',
    dataType: ValueType.TEXT,
    headerText: '시스템유형',
    width: '150',
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'system_code',
    dataType: ValueType.TEXT,
    headerText: '시스템코드',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'menu_type',
    dataType: ValueType.TEXT,
    headerText: '메뉴 구분',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'pgm_type',
    dataType: ValueType.TEXT,
    headerText: '프로그램 구분',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'pgm_id',
    dataType: ValueType.TEXT,
    headerText: '프로그램 ID',
    width: '150',
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'pgm_url',
    dataType: ValueType.TEXT,
    headerText: '프로그램 URL',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'sort_seq',
    dataType: ValueType.NUMBER,
    headerText: '정렬순서',
    width: '80',
    editable: true,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'pgm_param',
    dataType: ValueType.TEXT,
    headerText: '프로그램 파라미터',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'use_yn',
    dataType: ValueType.TEXT,
    headerText: '사용여부',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'select_yn',
    dataType: ValueType.TEXT,
    headerText: '조회선택여부',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'print_yn',
    dataType: ValueType.TEXT,
    headerText: '인쇄여부',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'save_yn',
    dataType: ValueType.TEXT,
    headerText: '저장여부',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'custom_yn',
    dataType: ValueType.TEXT,
    headerText: '커스텀여부',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'auth_kind',
    dataType: ValueType.TEXT,
    headerText: '권한종류',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'row_stat',
    dataType: ValueType.TEXT,
    headerText: '',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
];
