import { ValueType } from 'realgrid';

export const Config = [
  {
    fieldName: 'menu_name',
    dataType: ValueType.TEXT,
    headerText: '메뉴명',
    width: 350,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'menu_type',
    dataType: ValueType.TEXT,
    headerText: '메뉴 구분',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'menu_sno',
    dataType: ValueType.NUMBER,
    headerText: '메뉴일련번호',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'run_sno',
    dataType: ValueType.NUMBER,
    headerText: '실행일련번호',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'menu_tree_sno',
    dataType: ValueType.TEXT,
    headerText: '트리메뉴 일련번호',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'parent_menu_tree_sno',
    dataType: ValueType.TEXT,
    headerText: '부모 트리메뉴번호',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'tree_level',
    dataType: ValueType.NUMBER,
    headerText: '트리 Level',
    width: 30,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'pgm_id',
    dataType: ValueType.TEXT,
    headerText: '프로그램ID',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'pgm_type',
    dataType: ValueType.TEXT,
    headerText: '프로그램타입',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'pgm_url',
    dataType: ValueType.TEXT,
    headerText: '프로그램URL',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'system_type',
    dataType: ValueType.TEXT,
    headerText: '시스템타입',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'sort_seq',
    dataType: ValueType.NUMBER,
    headerText: '정렬순서',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'use_yn',
    dataType: ValueType.TEXT,
    headerText: '사용 여부',
    width: 70,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'save_yn',
    dataType: ValueType.TEXT,
    headerText: '저장여부',
    width: 70,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'select_yn',
    dataType: ValueType.TEXT,
    headerText: '조회여부',
    width: 70,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'print_yn',
    dataType: ValueType.TEXT,
    headerText: '인쇄여부',
    width: 70,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'custom_yn',
    dataType: ValueType.TEXT,
    headerText: '커스텀여부',
    width: 70,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  // {
  //   fieldName: 'user_name',
  //   dataType: ValueType.TEXT,
  //   headerText: '사용자명',
  //   width: 100,
  //   editable: false,
  //   textAlignment: 'center',
  //   visible: false,
  // },
  {
    fieldName: 'user_level',
    dataType: ValueType.INT,
    headerText: '레벨',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'emp_no',
    dataType: ValueType.TEXT,
    headerText: '사원번호',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },

  {
    fieldName: 'remark',
    dataType: ValueType.TEXT,
    headerText: '비고',
    width: 150,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'email',
    dataType: ValueType.TEXT,
    headerText: '',
    width: 0,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'first_rg_idf',
    dataType: ValueType.TEXT,
    headerText: '',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'first_rg_yms',
    dataType: ValueType.DATETIME,
    headerText: '',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'last_update_idf',
    dataType: ValueType.TEXT,
    headerText: '',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'last_update_yms',
    dataType: ValueType.DATETIME,
    headerText: '',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'pwd',
    dataType: ValueType.TEXT,
    headerText: '',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'row_stat',
    dataType: ValueType.TEXT,
    headerText: '',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'tel_no',
    dataType: ValueType.TEXT,
    headerText: '',
    width: 0,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
];
