import { ValueType } from 'realgrid';

export const Config = [
  {
    fieldName: 'user_id',
    dataType: ValueType.TEXT,
    headerText: '사용자 ID',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'menu_sno',
    dataType: ValueType.NUMBER,
    headerText: '메뉴 일련번호',
    width: '100',
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: 'menu_name',
    dataType: ValueType.TEXT,
    headerText: '메뉴명',
    width: '150',
    editable: true,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'parent_menu_sno',
    dataType: ValueType.INT,
    headerText: '부모 메뉴 일련번호',
    width: '100',
    editable: true,
    visible: false,
    textAlignment: 'center',
  },
  {
    fieldName: 'sort_seq',
    dataType: ValueType.INT,
    headerText: '정렬순서',
    width: '100',
    editable: true,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: 'row_stat',
    dataType: ValueType.TEXT,
    headerText: '',
    width: '60',
    editable: false,
    textReadOnly: true,
    textAlignment: 'center',
    visible: false,
  },
];
