import { ValueType } from "realgrid";
import { GRIDSTYLETYPE } from "@vntgcorp/vntg-wdk-client";
import { DETAILFIELD } from "../util/constants";
import { GridConfigType } from "../util/Types";

export const Config: GridConfigType[] = [
  {
    fieldName: DETAILFIELD.CM_CODE_TYPE_ID,
    dataType: ValueType.TEXT,
    headerText: "공통 코드 유형 ID",
    width: 100,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: false,
  },
  {
    fieldName: DETAILFIELD.DETAIL_CODE_ID,
    dataType: ValueType.TEXT,
    headerText: "상세 코드 ID",
    width: 100,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.DETAIL_CODE_NAME,
    dataType: ValueType.TEXT,
    headerText: "상세 코드 명",
    width: 250,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTLEFT,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.SORT_SEQ,
    dataType: ValueType.TEXT,
    headerText: "정렬 순서",
    width: 70,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTRIGHT,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.USE_YN,
    dataType: ValueType.TEXT,
    headerText: "사용 여부",
    width: 70,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.ETC_CTNT1,
    dataType: ValueType.TEXT,
    headerText: "기타 내용1",
    width: 150,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTLEFT,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.ETC_CTNT2,
    dataType: ValueType.TEXT,
    headerText: "기타 내용2",
    width: 150,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTLEFT,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.ETC_CTNT3,
    dataType: ValueType.TEXT,
    headerText: "기타 내용3",
    width: 100,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTLEFT,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.ETC_CTNT4,
    dataType: ValueType.TEXT,
    headerText: "기타 내용4",
    width: 100,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTLEFT,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.ETC_CTNT5,
    dataType: ValueType.TEXT,
    headerText: "기타 내용5",
    width: 100,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTLEFT,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.ETC_DESC,
    dataType: ValueType.TEXT,
    headerText: "기타 설명",
    width: 100,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTLEFT,
    visible: true,
  },
  {
    fieldName: DETAILFIELD.VALID_START_DATE,
    dataType: ValueType.DATE,
    headerText: "유효 시작 일자",
    width: 100,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    datetimeFormat: "yyyy-MM-dd",
    visible: true,
  },
  {
    fieldName: DETAILFIELD.VALID_END_DATE,
    dataType: ValueType.DATE,
    headerText: "유효 종료 일자",
    width: 100,
    editable: true,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    datetimeFormat: "yyyy-MM-dd",
    visible: true,
  },
];
