import { ValueType } from 'realgrid';
import { FIELD } from '../utils/constants';

export const Config = [
  {
    fieldName: FIELD.REP_BUSI_PLACE_YN,
    dataType: ValueType.TEXT,
    headerText: '대표 사업장',
    header: {
      text: '대표 사업장',
    },
    width: 75,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.CORP_CODE,
    dataType: ValueType.TEXT,
    headerText: '법인 코드',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.BUSI_PLACE,
    dataType: ValueType.TEXT,
    headerText: '사업장 코드',
    header: {
      text: '사업장 코드',
    },
    width: 90,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.BUSINESS_NO,
    dataType: ValueType.TEXT,
    headerText: '사업자 등록 번호',
    header: {
      text: '사업자 등록 번호',
    },
    width: 110,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.BUSI_PLACE_NAME,
    dataType: ValueType.TEXT,
    headerText: '사업장 명',
    header: {
      text: '사업장 명',
    },
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.BUSI_PLACE_NAME_EN,
    dataType: ValueType.TEXT,
    headerText: '사업장 명(영문)',
    width: 150,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.BUSI_PLACE_SHT_NAME,
    dataType: ValueType.TEXT,
    headerText: '사업장 명(약어)',
    header: {
      text: '사업장 명(약어)',
    },
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.PRESIDENT,
    dataType: ValueType.TEXT,
    headerText: '대표자 명',
    header: {
      text: '대표자 명',
    },
    width: 80,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.PRESIDENT_EN,
    dataType: ValueType.TEXT,
    headerText: '대표자 명(영문)',
    width: 80,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.BIZ_TYPE,
    dataType: ValueType.TEXT,
    headerText: '업태',
    header: {
      text: '업태',
    },
    width: 150,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.BIZ_ITEM,
    dataType: ValueType.TEXT,
    headerText: '업종',
    header: {
      text: '업종',
    },
    width: 150,
    editable: false,
    textAlignment: 'center',
    visible: true,
  },
  {
    fieldName: FIELD.ZIP_CODE,
    dataType: ValueType.TEXT,
    headerText: '우편 번호',
    width: 70,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.ADDR,
    dataType: ValueType.TEXT,
    headerText: '주소',
    width: 200,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.ADDR_EN,
    dataType: ValueType.TEXT,
    headerText: '주소(영문)',
    width: 200,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.TEL_NO,
    dataType: ValueType.TEXT,
    headerText: '전화 번호',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.FAX_NO,
    dataType: ValueType.TEXT,
    headerText: '팩스 번호',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.TAX_OFFICE_CODE,
    dataType: ValueType.TEXT,
    headerText: '세무서 코드',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.HOMETAX_ID,
    dataType: ValueType.TEXT,
    headerText: '국세청 ID',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.SLAVE_BUSI_NO,
    dataType: ValueType.TEXT,
    headerText: '종속 사업자 번호',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.SUM_RECOG_NO,
    dataType: ValueType.TEXT,
    headerText: '',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.PRSD_SEC_NO,
    dataType: ValueType.TEXT,
    headerText: '',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.HOMEPAGE,
    dataType: ValueType.TEXT,
    headerText: '',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.CUST_CODE,
    dataType: ValueType.TEXT,
    headerText: '거래처 코드',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.ITEM_CODE,
    dataType: ValueType.TEXT,
    headerText: '종목 코드',
    width: 100,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.BIZ_DATE,
    dataType: ValueType.DATE,
    datetimeFormat: 'yyyy/MM/dd',
    headerText: '',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.REMARK,
    dataType: ValueType.TEXT,
    headerText: '비고',
    width: 150,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.BUSI_PART,
    dataType: ValueType.TEXT,
    headerText: '',
    width: 150,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.FIRST_RG_YMS,
    dataType: ValueType.TEXT,
    headerText: '최초 등록 일시',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.FIRST_RG_IDF,
    dataType: ValueType.TEXT,
    headerText: '최초 등록 식별자',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.LAST_UPDATE_YMS,
    dataType: ValueType.TEXT,
    headerText: '최종 업데이트 일시',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.LAST_UPDATE_IDF,
    dataType: ValueType.TEXT,
    headerText: '최종 업데이트 식별자',
    width: 60,
    editable: false,
    textAlignment: 'center',
    visible: false,
  },
  {
    fieldName: FIELD.ROW_STAT,
    visible: false,
  },
];
