import { ValueType } from "realgrid";
import { GRIDSTYLETYPE } from "@vntgcorp/vntg-wdk-client";
export const NoticeGridConfig = [
  {
    fieldName: "article_sno",
    dataType: ValueType.INT,
    headerText: "게시물 일련번호",
    width: 20,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: false,
  },
  {
    fieldName: "corp_code",
    dataType: ValueType.TEXT,
    headerText: "법인 코드",
    width: 20,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: false,
  },
  {
    fieldName: "busi_place",
    dataType: ValueType.TEXT,
    headerText: "사업장",
    width: 50,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: true,
  },
  {
    fieldName: "system_type",
    dataType: ValueType.TEXT,
    width: 80,
    headerText: "시스템 타입",
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: true,
  },
  {
    fieldName: "board_all_yn",
    dataType: ValueType.TEXT,
    width: 50,
    headerText: "게시 대상",
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: true,
  },
  {
    fieldName: "board_type",
    dataType: ValueType.TEXT,
    width: 50,
    headerText: "공지 유형",
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: true,
  },
  {
    fieldName: "title",
    dataType: ValueType.TEXT,
    headerText: "제목",
    width: 400,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTLEFT,
    visible: true,
  },
  {
    fieldName: "write_date",
    dataType: ValueType.DATETIME,
    headerText: "작성일자",
    width: 150,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: true,
    fieldDatetimeFormat: "iso",
    datetimeFormat: "yyyy-MM-dd HH:mm:ss",
    // displayCallback: function (grid, index, value) {
    //   if (!value) return undefined;
    //   else return getDate(value);
    // },
  },
  {
    fieldName: "write_user_id",
    dataType: ValueType.TEXT,
    headerText: "작성자 ID",
    width: 50,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: false,
  },
  {
    fieldName: "write_user_name",
    dataType: ValueType.TEXT,
    headerText: "작성자",
    width: 130,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: true,
  },
  {
    fieldName: "article_ctnt",
    dataType: ValueType.TEXT,
    width: 150,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: false,
  },
  {
    fieldName: "attach_group_id",
    dataType: ValueType.TEXT,
    headerText: "첨부파일",
    width: 150,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: false,
  },
  {
    fieldName: "attach_filename",
    dataType: ValueType.TEXT,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: false,
  },

  {
    fieldName: "row_stat",
    dataType: ValueType.TEXT,
    width: 40,
    editable: false,
    styleName: GRIDSTYLETYPE.TEXTCENTER,
    visible: false,
  },
];
